### PR TITLE
Update NOTICE.md file

### PR DESCRIPTION
**Pull request by jopit**
Signed-off-by: John Pitman <jspitman@ca.ibm.com>

### CODE REVIEW

**Comment by jopit** [comment]
@NikCanvin can you answer Erin's question above?

**Comment by NikCanvin** [comment]
We have a single NOTICE file for all Eclipse Codewind, to streamline legal work
(It is not an issue to over declare packages / attribute copyrights)
(It is an issue to under lest them though)
..
however, this PR is now superceded by: 
https://github.com/eclipse/codewind-eclipse/pull/472
https://github.com/eclipse/codewind-eclipse/pull/473

**Comment by jopit** [comment]
@NikCanvin  Erin isn't really asking why the notices file for the eclipse plugin includes node dependencies, she's asking why the eclipse plugin's java dependencies are not included.

**Comment by NikCanvin** [comment]
moved disucssion to a Slack thread

**Pull request closed without merging**
