### PR TITLE
raise versions to 0.8.1 for ifix

### PR DESCRIPTION
**Pull request by tobespc**
Signed-off-by: Toby Corbin <corbint@uk.ibm.com>

### CODE REVIEW

**Comment by jopit** [comment]
The version of the core plugin also should be incremented

**Comment by josephca** [comment]
> Should also increment the version of the core plugin

Done!

**Comment by eharris369** [comment]
Now the version in dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF is the same as it is for 0.9.0.  Do we need to update this for an ifix or is the build data good enough?

**Comment by josephca** [comment]
> Now the version in dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF is the same as it is for 0.9.0. Do we need to update this for an ifix or is the build date good enough?

The build date would work without version update. However, it would be better to increment the version for 0.9.0  accordingly i.e. 1.5.3.

**Comment by eharris369** [comment]
But what if we need to make another ifix for 0.8.0 later on?

**Comment by jopit** [comment]
We should probably be following the Eclipse versioning guidelines: https://wiki.eclipse.org/Version_Numbering#When_to_change_the_service_segment which covers this case

**Pull request merged**
